---
title: "Higher Performance Computing: Geo"
author: "Alex Mandel"
date: "April 30, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## What is HPC

* What is High Performance?
* Why do you care?

## Definitions

* i/o (aka Input/Output): Reading and Writing from Disk
* parallel: Doing things at the same time
* CPU: The calculator
    * Cores: Physical Number of Calculators
    * Threads: Number of lines Cores can service
* memory(RAM): The place the computer puts things it's currently working on
* storage: The place you put things you want to keep


## All about Approach

1. Write a solution to a problem
2. Look for things in series that could be done in parallel (Independence Test)
3. Split into function
4. Iterate function in parallel
5. Collate the answers (if necessary)

## Keep it Simple

* map + reduce, split + combine, independant + aggregate

**High end stuff**

* Hadoop
* Spark
* MPI (Message Passing Interface)
* Microservices (e.g. AWS Lambda)

## Profiling

Finding the limiting factor:

* RAM
    * Expensive
* CPU - more is great but:
    * slower clock speed
    * RAM per CPU
* Disk
    * Fast or Big, local or network?

You have to find the limit to figure out how to go faster.

* System Monitor
* Logging in code (including time stamp and memory usage)
* Code profiling tools (memory management)

## Hardware

*Simple/Slower*

* Laptop
* Desktop
* Server
* Bunch of Servers
* Cluster or Cloud

*Complex/Faster*

## What's Available

* College or Reserch Clusters
     * CAES Farm
     * etc...
* Amazon Web Services
* Google Compute Engine
* Microsoft Azure

## Part 2: Examples

* [Make thing independant]()
* [Do things at the same time](https://github.com/wildintellect/lenscorrection)

## Geo Problems

* Calculate answer by geography where neighbors don't matter
   * By Country, State, County, City, etc...
   * By Pixel, Stack of Pixels
* Do the same thing over many files
   * Batch reprojection & format conversion

## Geo Problems that don't parallel easily

* Where your value depends on your neighbor's value
    * Interpolation
* Data can't be split into subsets (sum of parts != sum of whole)
* Edge effects